/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lessence.gymmaven.GUI;

import com.lessence.gymmaven.clases.Actividades_Socios_Turnos;
import com.lessence.gymmaven.clases.HibernateUtil;
import com.lessence.gymmaven.clases.ParametrosSistema;
import com.lessence.gymmaven.clases.RegistroAsistencias;
import com.lessence.gymmaven.clases.Socios;
import java.awt.Color;
import java.awt.Image;
import java.awt.SystemColor;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author Emiliano
 */
public class Accesos extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Asistencias
     */
    public String Base;
    public String Usuario;
    public String Clave;
    public String Recuento = "";

    Thread hilo;

    public Accesos() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        jcbPasesNegativos.setVisible(false);
        IniciodeVentana();
        this.setTitle(ParametrosSistema.getNombreEmpresa() + " - Control de Asistencias");
//        String path = ParametrosSistema.getImagenEmpresa();
//        URL url = this.getClass().getResource(path);
//        ImageIcon icon = new ImageIcon(url);
//        jlImagenEmpresa.setIcon(icon);

        Reloj();

//        JOptionPane jpo = new JOptionPane();
//        jpo.setFont(Font.decode("BankGothic Lt BT"));
//        Object[] options = {"CANCELAR", "IMPRIMIR"};
//        jpo.showOptionDialog(null, "Elige imprimir o cancelar", "Aviso",
//                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
//                null, options, options[0]);
    }

    Accesos(int i) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        IniciodeVentana();
        this.setTitle(ParametrosSistema.getNombreEmpresa() + " - Control de Asistencias");
        jcbPasesNegativos.setVisible(true);

    }

    /**
     *
     */
    public void Reloj() { //Constructor 
        hilo = new Thread(this);
        hilo.start();

    } //fin constructor 

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == hilo) {
            try {
                Hora(jlHora);
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                System.out.println(ex.getMessage());
            }

        }
    }

    public void Hora(JLabel label) {
        String horaActual = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss").format(Date.from(Instant.now()));
        label.setText(horaActual);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ParametrosSistema.getImagenEmpresa());
        return retValue;
    }

    public void IniciodeVentana() {
        for (int i = 0; i < 9; i++) {
            jLNombre.setText("");
            jTActividades.setText("");
            jLPasesDisponibles.setText("");
            jTDocumento.setText("");
            jLBienvenido.setVisible(false);
            jTDocumento.requestFocus();
            jLabel8.setForeground(Color.black);
            jPanel6.setBackground(Color.lightGray);
            jlActividades.setVisible(false);
            jLAct1.setText("");
            jLAct2.setText("");
            jLAct3.setText("");
            jLAct4.setText("");
            jLAct5.setText("");
        }

        jTDocumento.requestFocus();
    }

//             }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLAct1 = new javax.swing.JLabel();
        jLAct4 = new javax.swing.JLabel();
        jLAct3 = new javax.swing.JLabel();
        jLAct2 = new javax.swing.JLabel();
        jLAct5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLPasesDisponibles = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlActividades = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTActividades = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTDocumento = new javax.swing.JTextField();
        jLBienvenido = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlHora = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlImagenEmpresa = new javax.swing.JLabel();
        jcbPasesNegativos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("L'Essence - Control de Asistencias");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(822, 530));

        jLAct1.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLAct1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLAct4.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLAct4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLAct3.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLAct3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLAct2.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLAct2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLAct5.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLAct5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLAct1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addComponent(jLAct2, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addComponent(jLAct3, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addComponent(jLAct4, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addComponent(jLAct5, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAct1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAct2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAct3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAct4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLAct5)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLAct1, jLAct2, jLAct3, jLAct4, jLAct5});

        jPanel4.setMinimumSize(new java.awt.Dimension(12, 80));

        jLPasesDisponibles.setFont(new java.awt.Font("BankGothic Lt BT", 0, 36)); // NOI18N
        jPanel4.add(jLPasesDisponibles);

        jlActividades.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlActividades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlActividades.setText("Tus Actividades");
        jlActividades.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlActividades))
        );

        jLabel8.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel8.setText("Que rutina vas a hacer hoy?");

        jTActividades.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jTActividades.setForeground(new java.awt.Color(255, 51, 0));
        jTActividades.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTActividades.setToolTipText("");
        jTActividades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTActividades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTActividadesKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTActividades, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jPanel13.add(jPanel6);

        jLabel2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Por favor, ingresá tu Número de Documento");

        jTDocumento.setFont(new java.awt.Font("BankGothic Lt BT", 0, 36)); // NOI18N
        jTDocumento.setForeground(new java.awt.Color(255, 0, 0));
        jTDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTDocumento.setMinimumSize(new java.awt.Dimension(600, 50));
        jTDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTDocumentoKeyPressed(evt);
            }
        });

        jLBienvenido.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBienvenido.setText("Bienvenido");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10);

        jLNombre.setFont(new java.awt.Font("BankGothic Lt BT", 0, 36)); // NOI18N
        jLNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLNombre);

        jlHora.setBackground(new java.awt.Color(255, 0, 0));
        jlHora.setFont(new java.awt.Font("BankGothic Lt BT", 1, 24)); // NOI18N
        jlHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHora.setText("05-09-2016 - 15:25");
        jlHora.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlImagenEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlImagenEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Lessence.png"))); // NOI18N
        jlImagenEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlImagenEmpresaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlImagenEmpresa)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlImagenEmpresa)
                .addContainerGap())
        );

        jcbPasesNegativos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jcbPasesNegativos.setText("Habilita pases negativos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbPasesNegativos)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbPasesNegativos))
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jTActividadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTActividadesKeyPressed
        if (evt.getKeyCode() == 10) {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            if ("".equals(jTDocumento.getText())) {
                JOptionPane.showMessageDialog(this, "Debe ingresar su identificación", "Registro de Asistencias", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(jTActividades.getText())) {
                JOptionPane.showMessageDialog(this, "Debe ingresar una opción de Actividad", "Registro de Asistencias", JOptionPane.ERROR_MESSAGE);
            } else {
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(Date.from(Instant.now()));
                calendar.add(Calendar.DAY_OF_YEAR, ParametrosSistema.getAvisoVencimientos());
                List<Actividades_Socios_Turnos> listaActividades = Actividades_Socios_Turnos.listaActividades_Socios_Turnos();
                RegistroAsistencias asistencia = new RegistroAsistencias();
                sesion.beginTransaction();
                int listaActividadesSize = listaActividades.size();
                for (int i = 0; i < listaActividadesSize; i++) {
                    Actividades_Socios_Turnos relacion = listaActividades.get(i);
                    if (relacion.getSocio().getPersona().getDNI().equals(jTDocumento.getText())) {
                        if (relacion.getRelacion().getActividad().getIdActividad() == Integer.parseInt(jTActividades.getText())) {
                            if (relacion.getSocio().getEstado().getIdEstado() == 1) {

                                if (relacion.getPaseLibre() == 1) {
                                    //No descuenta pases
                                    asistencia.setFecha(Date.from(Instant.now()));
                                    asistencia.setSocio(relacion.getSocio());
                                    asistencia.setRelacion(relacion.getRelacion());
                                    sesion.save(asistencia);
                                    sesion.getTransaction().commit();

                                    if (relacion.getSocio().getPrimerVencimiento().before(calendar.getTime())) {
                                        new Form_AvisoVencimientos(this, rootPaneCheckingEnabled, relacion.getSocio().getPrimerVencimiento()).setVisible(rootPaneCheckingEnabled);
                                    }
                                    new Form_AvisoAccesoCorrecto(this, rootPaneCheckingEnabled).setVisible(rootPaneCheckingEnabled);
                                    jLNombre.setText("");
                                    jTActividades.setText("");
                                    jLPasesDisponibles.setText("");
                                    jTDocumento.setText("");
                                    jTDocumento.requestFocus();
                                    Recuento = "";
                                    IniciodeVentana();
                                } else if (jcbPasesNegativos.isSelected()) {
                                    asistencia.setFecha(Date.from(Instant.now()));
                                    asistencia.setSocio(relacion.getSocio());
                                    asistencia.setRelacion(relacion.getRelacion());
                                    relacion.setPases(relacion.getPases() - 1);
                                    jLPasesDisponibles.setText("Te quedan " + relacion.getPases() + " pases disponibles");
                                    sesion.save(asistencia);
                                    sesion.update(relacion);
                                    sesion.getTransaction().commit();
                                    jLNombre.setText("");
                                    jTActividades.setText("");
                                    jLPasesDisponibles.setText("");
                                    jTDocumento.setText("");
                                    jTDocumento.requestFocus();
                                    Recuento = "";
                                    IniciodeVentana();
                                } else if (relacion.getPases() >= 1) {
                                    asistencia.setFecha(Date.from(Instant.now()));
                                    asistencia.setSocio(relacion.getSocio());
                                    asistencia.setRelacion(relacion.getRelacion());
                                    relacion.setPases(relacion.getPases() - 1);
                                    jLPasesDisponibles.setText("Te quedan " + relacion.getPases() + " pases disponibles");
                                    new Form_AvisoAccesoCorrecto(this, rootPaneCheckingEnabled).setVisible(rootPaneCheckingEnabled);
                                    sesion.save(asistencia);
                                    sesion.update(relacion);
                                    sesion.getTransaction().commit();

                                    if (relacion.getSocio().getPrimerVencimiento().before(calendar.getTime())) {
                                        new Form_AvisoVencimientos(this, rootPaneCheckingEnabled, relacion.getSocio().getPrimerVencimiento()).setVisible(rootPaneCheckingEnabled);
                                    }
                                    jLNombre.setText("");
                                    jTActividades.setText("");
                                    jLPasesDisponibles.setText("");
                                    jTDocumento.setText("");
                                    jTDocumento.requestFocus();
                                    Recuento = "";
                                    IniciodeVentana();
                                } else {
                                    JOptionPane.showMessageDialog(this, "No quedan pases disponibles para la actividad.", "Control de Asistencias - L´Essence", JOptionPane.INFORMATION_MESSAGE);
                                    jTActividades.setText("");
                                    jTDocumento.setText("");
                                    jTDocumento.requestFocus();
                                    IniciodeVentana();
                                }
                            } else {
                                new Form_AvisoInactivos(this, rootPaneCheckingEnabled).setVisible(rootPaneCheckingEnabled);
                                jTActividades.setText("");
                                jTDocumento.setText("");
                                jTDocumento.requestFocus();
                                IniciodeVentana();

                            }
                        }
                    }
                }

            }
            sesion.close();
            IniciodeVentana();
        }

    }//GEN-LAST:event_jTActividadesKeyPressed

    private void jTDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDocumentoKeyPressed
        boolean existeSocio = false;
        boolean tieneActividades = false;
        int tecla = evt.getKeyCode();

        switch (tecla) {
            case 106:
                new Form_Asitencias_Profesores(this, rootPaneCheckingEnabled).setVisible(true);
                jTDocumento.setText("");
                break;

            case 10:
                if ("".equals(jTDocumento.getText())) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar su identificación", "Registro de Asistencias", JOptionPane.ERROR_MESSAGE);
                } else {
                    List<Socios> listaSocios = Socios.listaSocios("From Socios where situacion = 1");
                    for (int r = 0; r < listaSocios.size(); r++) {
                        Socios socio = listaSocios.get(r);
                        if (socio.getPersona().getDNI().equals(jTDocumento.getText())) {
                            existeSocio = true;
                            r = listaSocios.size();

                            jLBienvenido.setVisible(true);
                            jLNombre.setText(socio.getPersona().getNombre());
                            //Verifico si el socio esta inactivo y muestro el cartel
                            if (socio.getPrimerVencimiento().before(Date.from(Instant.now()))) {

                                new Form_AvisoInactivos(this, true).setVisible(true);
                                jTDocumento.setText("");
                                jTDocumento.requestFocus();
                                jLBienvenido.setVisible(false);
                                jLNombre.setText("");
                                tieneActividades = false;

                            } else {
                                List<Actividades_Socios_Turnos> listaActividades = Actividades_Socios_Turnos.listaActividades_Socios_Turnos("From Actividades_Socios_Turnos where socio=" + socio.getIdSocio());
                                tieneActividades = true;
                                jlActividades.setVisible(true);
                                for (int i = 0; i < listaActividades.size(); i++) {
                                    Actividades_Socios_Turnos relaciones = listaActividades.get(i);

                                    switch (i) {
                                        case 0:
                                            jLAct1.setText(relaciones.getRelacion().getActividad().getIdActividad() + " - " + relaciones.getRelacion().getActividad().getActividad());
                                            jLAct1.setVisible(true);
                                            i++;
                                            break;
                                        case 1:
                                            jLAct2.setText(relaciones.getRelacion().getActividad().getIdActividad() + " - " + relaciones.getRelacion().getActividad().getActividad());
                                            jLAct2.setVisible(true);
                                            i++;
                                            break;
                                        case 2:
                                            jLAct3.setText(relaciones.getRelacion().getActividad().getIdActividad() + " - " + relaciones.getRelacion().getActividad().getActividad());
                                            jLAct3.setVisible(true);
                                            i++;
                                            break;
                                        case 3:
                                            jLAct4.setText(relaciones.getRelacion().getActividad().getIdActividad() + " - " + relaciones.getRelacion().getActividad().getActividad());
                                            jLAct4.setVisible(true);
                                            i++;
                                            break;
                                        case 4:
                                            jLAct5.setText(relaciones.getRelacion().getActividad().getIdActividad() + " - " + relaciones.getRelacion().getActividad().getActividad());
                                            jLAct5.setVisible(true);
                                            i++;
                                            break;
                                        default:
                                            break;
                                    }
                                }
                            }

//                            }
                        }

                    }
                    if (existeSocio == false) {
                        JOptionPane.showMessageDialog(this, "El documento ingresado no coincide con un socio con actividades asignadas.\nVerifique los datos.",
                                "Gestión de Asistencias", JOptionPane.ERROR_MESSAGE);
                        jTDocumento.setText("");
                        jTDocumento.requestFocus();
                    } else {

                        if (tieneActividades == true) {
                            jPanel6.setBackground(Color.red);
                            jLabel8.setForeground(SystemColor.control);
                            jTActividades.requestFocus();
                        }
                    }
                }
                break;
        }


    }//GEN-LAST:event_jTDocumentoKeyPressed

    private void jlImagenEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlImagenEmpresaMouseClicked
        new Inicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlImagenEmpresaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAct1;
    private javax.swing.JLabel jLAct2;
    private javax.swing.JLabel jLAct3;
    private javax.swing.JLabel jLAct4;
    private javax.swing.JLabel jLAct5;
    private javax.swing.JLabel jLBienvenido;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPasesDisponibles;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTActividades;
    private javax.swing.JTextField jTDocumento;
    private javax.swing.JCheckBox jcbPasesNegativos;
    private javax.swing.JLabel jlActividades;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel jlImagenEmpresa;
    // End of variables declaration//GEN-END:variables
}
