/*
 * Copyright 2016 Emiliano Policardo http://www.facebook.com/policomputacion.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.lessence.gymmaven.GUI;

import com.lessence.gymmaven.clases.Caja_diaria;
import com.lessence.gymmaven.clases.FormasPago;
import com.lessence.gymmaven.clases.HibernateUtil;
import com.lessence.gymmaven.clases.ParametrosSistema;
import java.awt.Color;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Criteria;
import org.hibernate.Session;

/**
 *
 * @author Emiliano Policardo http://www.facebook.com/policomputacion
 */
public class Form_Arqueo extends javax.swing.JFrame {

    /**
     * Creates new form Form_Arqueo
     */
    public Form_Arqueo() {
        initComponents();
        HabilitarPanelArqueoSistema();
        HabilitarPanelDiferencia();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPMovimientosSistema = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jT_Sist_Efectivo = new javax.swing.JTextField();
        jT_Sist_Credito = new javax.swing.JTextField();
        jT_Sist_Debito = new javax.swing.JTextField();
        jT_Sist_Cheques = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jT_Sist_Egresos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jT_Sist_Caja = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jT_Sist_Total = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jB_CalcularDiferencias = new javax.swing.JButton();
        jPResultado = new javax.swing.JPanel();
        jT_Dif_Efectivo = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jT_Dif_Egresos = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jT_Dif_Creditos = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jT_Dif_Debitos = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jT_Dif_Cheques = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jT_Dif_Total = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jB_CerrarCaja = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jT_Resultado_Efectivo = new javax.swing.JTextField();
        jPMoneda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jT_1 = new javax.swing.JTextField();
        jT_005 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jT_100 = new javax.swing.JTextField();
        jT_50 = new javax.swing.JTextField();
        jT_20 = new javax.swing.JTextField();
        jT_10 = new javax.swing.JTextField();
        jT_5 = new javax.swing.JTextField();
        jT_2 = new javax.swing.JTextField();
        jT_050 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jT_025 = new javax.swing.JTextField();
        jT_010 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jT_500 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jT_Debito = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jT_Credito = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jT_Cheques = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jT_Arqueo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jT_Egresos_Arqueo = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Arqueo de Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BankGothic Lt BT", 0, 14))); // NOI18N

        jPMovimientosSistema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos según Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BankGothic Lt BT", 0, 14))); // NOI18N

        jLabel35.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel35.setText("Ingresos en Efectivo");
        jLabel35.setEnabled(false);

        jT_Sist_Efectivo.setEditable(false);
        jT_Sist_Efectivo.setBackground(new java.awt.Color(255, 255, 255));
        jT_Sist_Efectivo.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Sist_Efectivo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Sist_Efectivo.setEnabled(false);

        jT_Sist_Credito.setEditable(false);
        jT_Sist_Credito.setBackground(new java.awt.Color(255, 255, 255));
        jT_Sist_Credito.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Sist_Credito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Sist_Credito.setEnabled(false);

        jT_Sist_Debito.setEditable(false);
        jT_Sist_Debito.setBackground(new java.awt.Color(255, 255, 255));
        jT_Sist_Debito.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Sist_Debito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Sist_Debito.setEnabled(false);

        jT_Sist_Cheques.setEditable(false);
        jT_Sist_Cheques.setBackground(new java.awt.Color(255, 255, 255));
        jT_Sist_Cheques.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Sist_Cheques.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Sist_Cheques.setEnabled(false);

        jLabel32.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel32.setText("Cheques");
        jLabel32.setEnabled(false);

        jLabel34.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel34.setText("Tarjetas de Crédito");
        jLabel34.setEnabled(false);

        jLabel33.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel33.setText("Tarjetas de Débito");
        jLabel33.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel19.setText("Egresos");
        jLabel19.setEnabled(false);

        jT_Sist_Egresos.setEditable(false);
        jT_Sist_Egresos.setBackground(new java.awt.Color(255, 255, 255));
        jT_Sist_Egresos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Sist_Egresos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Sist_Egresos.setEnabled(false);
        jT_Sist_Egresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Sist_EgresosActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel9.setText("$");
        jLabel9.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel13.setText("$");
        jLabel13.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel16.setText("$");
        jLabel16.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel18.setText("$");
        jLabel18.setEnabled(false);

        jLabel42.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel42.setText("$");
        jLabel42.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel14.setText("Caja Inicial");
        jLabel14.setEnabled(false);

        jT_Sist_Caja.setEditable(false);
        jT_Sist_Caja.setBackground(new java.awt.Color(255, 255, 255));
        jT_Sist_Caja.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Sist_Caja.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Sist_Caja.setEnabled(false);
        jT_Sist_Caja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_Sist_CajaFocusGained(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel43.setText("$");
        jLabel43.setEnabled(false);

        jLabel31.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLabel31.setText("Total Sistema");
        jLabel31.setEnabled(false);

        jT_Sist_Total.setEditable(false);
        jT_Sist_Total.setBackground(new java.awt.Color(255, 255, 255));
        jT_Sist_Total.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Sist_Total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Sist_Total.setEnabled(false);

        jLabel44.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel44.setText("$");
        jLabel44.setEnabled(false);

        javax.swing.GroupLayout jPMovimientosSistemaLayout = new javax.swing.GroupLayout(jPMovimientosSistema);
        jPMovimientosSistema.setLayout(jPMovimientosSistemaLayout);
        jPMovimientosSistemaLayout.setHorizontalGroup(
            jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMovimientosSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMovimientosSistemaLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_Sist_Efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMovimientosSistemaLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_Sist_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMovimientosSistemaLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_Sist_Debito, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMovimientosSistemaLayout.createSequentialGroup()
                        .addGroup(jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPMovimientosSistemaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMovimientosSistemaLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMovimientosSistemaLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)))
                        .addGap(4, 4, 4)
                        .addGroup(jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_Sist_Egresos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jT_Sist_Cheques, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jT_Sist_Caja, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPMovimientosSistemaLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_Sist_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPMovimientosSistemaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jT_Sist_Cheques, jT_Sist_Credito, jT_Sist_Debito, jT_Sist_Efectivo, jT_Sist_Egresos});

        jPMovimientosSistemaLayout.setVerticalGroup(
            jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMovimientosSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jT_Sist_Efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Sist_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Sist_Debito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Sist_Cheques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jT_Sist_Egresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jT_Sist_Caja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMovimientosSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jT_Sist_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel44)))
                .addContainerGap())
        );

        jButton3.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jButton3.setText("Arquear Sistema");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jB_CalcularDiferencias.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jB_CalcularDiferencias.setText("Calcular Diferencias");
        jB_CalcularDiferencias.setEnabled(false);
        jB_CalcularDiferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CalcularDiferenciasActionPerformed(evt);
            }
        });

        jPResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado del Arqueo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BankGothic Lt BT", 0, 14))); // NOI18N

        jT_Dif_Efectivo.setEditable(false);
        jT_Dif_Efectivo.setBackground(new java.awt.Color(255, 255, 255));
        jT_Dif_Efectivo.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Dif_Efectivo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Dif_Efectivo.setEnabled(false);

        jLabel45.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel45.setText("Egresos");
        jLabel45.setEnabled(false);

        jT_Dif_Egresos.setEditable(false);
        jT_Dif_Egresos.setBackground(new java.awt.Color(255, 255, 255));
        jT_Dif_Egresos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Dif_Egresos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Dif_Egresos.setEnabled(false);
        jT_Dif_Egresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Dif_EgresosActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel46.setText("$");
        jLabel46.setEnabled(false);

        jT_Dif_Creditos.setEditable(false);
        jT_Dif_Creditos.setBackground(new java.awt.Color(255, 255, 255));
        jT_Dif_Creditos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Dif_Creditos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Dif_Creditos.setEnabled(false);

        jLabel47.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel47.setText("$");
        jLabel47.setEnabled(false);

        jT_Dif_Debitos.setEditable(false);
        jT_Dif_Debitos.setBackground(new java.awt.Color(255, 255, 255));
        jT_Dif_Debitos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Dif_Debitos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Dif_Debitos.setEnabled(false);

        jLabel48.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel48.setText("Cheques");
        jLabel48.setEnabled(false);

        jLabel49.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel49.setText("$");
        jLabel49.setEnabled(false);

        jT_Dif_Cheques.setEditable(false);
        jT_Dif_Cheques.setBackground(new java.awt.Color(255, 255, 255));
        jT_Dif_Cheques.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Dif_Cheques.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Dif_Cheques.setEnabled(false);

        jLabel50.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel50.setText("Tarjetas de Débito");
        jLabel50.setEnabled(false);

        jLabel51.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel51.setText("$");
        jLabel51.setEnabled(false);

        jLabel52.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel52.setText("Tarjetas de Crédito");
        jLabel52.setEnabled(false);

        jLabel54.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLabel54.setText("Total Diferencias");
        jLabel54.setEnabled(false);

        jLabel55.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel55.setText("Ingresos en Efectivo");
        jLabel55.setEnabled(false);

        jT_Dif_Total.setEditable(false);
        jT_Dif_Total.setBackground(new java.awt.Color(255, 255, 255));
        jT_Dif_Total.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Dif_Total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Dif_Total.setEnabled(false);

        jLabel57.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel57.setText("$");
        jLabel57.setEnabled(false);

        jLabel58.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel58.setText("$");
        jLabel58.setEnabled(false);

        javax.swing.GroupLayout jPResultadoLayout = new javax.swing.GroupLayout(jPResultado);
        jPResultado.setLayout(jPResultadoLayout);
        jPResultadoLayout.setHorizontalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPResultadoLayout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_Dif_Debitos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPResultadoLayout.createSequentialGroup()
                        .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPResultadoLayout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPResultadoLayout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel49)))
                        .addGap(4, 4, 4)
                        .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_Dif_Egresos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jT_Dif_Cheques, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                    .addGroup(jPResultadoLayout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_Dif_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPResultadoLayout.createSequentialGroup()
                        .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPResultadoLayout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel58))
                            .addGroup(jPResultadoLayout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel46)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_Dif_Creditos, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jT_Dif_Efectivo))))
                .addContainerGap())
        );

        jPResultadoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jT_Dif_Cheques, jT_Dif_Creditos, jT_Dif_Debitos, jT_Dif_Egresos});

        jPResultadoLayout.setVerticalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jT_Dif_Efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Dif_Creditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Dif_Debitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Dif_Cheques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jT_Dif_Egresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jT_Dif_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel57)))
                .addContainerGap())
        );

        jB_CerrarCaja.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14)); // NOI18N
        jB_CerrarCaja.setText("Cerrar caja");
        jB_CerrarCaja.setEnabled(false);
        jB_CerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CerrarCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPMovimientosSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jB_CalcularDiferencias))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB_CerrarCaja)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPMovimientosSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_CalcularDiferencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_CerrarCaja)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel20.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel20.setText("Resultado del Efectivo");

        jT_Resultado_Efectivo.setEditable(false);
        jT_Resultado_Efectivo.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Resultado_Efectivo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel1.setText("$0.50");

        jT_1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_1.setForeground(java.awt.Color.lightGray);
        jT_1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_1.setText("0");
        jT_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_1FocusLost(evt);
            }
        });

        jT_005.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_005.setForeground(java.awt.Color.lightGray);
        jT_005.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_005.setText("0");
        jT_005.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_005FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_005FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel3.setText("$2");

        jLabel4.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel4.setText("$5");

        jLabel5.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel5.setText("$10");

        jLabel6.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel6.setText("$20");

        jLabel7.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel7.setText("$50");

        jLabel8.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel8.setText("$100");

        jLabel10.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel10.setText("$0.05");

        jLabel11.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel11.setText("$0.10");

        jLabel12.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel12.setText("$0.25");

        jT_100.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_100.setForeground(java.awt.Color.lightGray);
        jT_100.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_100.setText("0");
        jT_100.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_100FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_100FocusLost(evt);
            }
        });

        jT_50.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_50.setForeground(java.awt.Color.lightGray);
        jT_50.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_50.setText("0");
        jT_50.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_50FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_50FocusLost(evt);
            }
        });

        jT_20.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_20.setForeground(java.awt.Color.lightGray);
        jT_20.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_20.setText("0");
        jT_20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_20FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_20FocusLost(evt);
            }
        });

        jT_10.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_10.setForeground(java.awt.Color.lightGray);
        jT_10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_10.setText("0");
        jT_10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_10FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_10FocusLost(evt);
            }
        });

        jT_5.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_5.setForeground(java.awt.Color.lightGray);
        jT_5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_5.setText("0");
        jT_5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_5FocusLost(evt);
            }
        });

        jT_2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_2.setForeground(java.awt.Color.lightGray);
        jT_2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_2.setText("0");
        jT_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_2FocusLost(evt);
            }
        });

        jT_050.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_050.setForeground(java.awt.Color.lightGray);
        jT_050.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_050.setText("0");
        jT_050.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_050FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_050FocusLost(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel21.setText("$1.00");

        jT_025.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_025.setForeground(java.awt.Color.lightGray);
        jT_025.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_025.setText("0");
        jT_025.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_025FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_025FocusLost(evt);
            }
        });

        jT_010.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_010.setForeground(java.awt.Color.lightGray);
        jT_010.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_010.setText("0");
        jT_010.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_010FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_010FocusLost(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel24.setText("$500");

        jT_500.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_500.setForeground(java.awt.Color.lightGray);
        jT_500.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_500.setText("0");
        jT_500.setNextFocusableComponent(jT_100);
        jT_500.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_500FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_500FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPMonedaLayout = new javax.swing.GroupLayout(jPMoneda);
        jPMoneda.setLayout(jPMonedaLayout);
        jPMonedaLayout.setHorizontalGroup(
            jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMonedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMonedaLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_500, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMonedaLayout.createSequentialGroup()
                        .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_100, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPMonedaLayout.createSequentialGroup()
                                .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_025, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT_010, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT_005, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT_050, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPMonedaLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPMonedaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jT_005, jT_010, jT_025, jT_050, jT_1, jT_10, jT_100, jT_2, jT_20, jT_5, jT_50});

        jPMonedaLayout.setVerticalGroup(
            jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMonedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPMonedaLayout.createSequentialGroup()
                        .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPMonedaLayout.createSequentialGroup()
                                .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jT_100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPMonedaLayout.createSequentialGroup()
                        .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jT_500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24))
                            .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jT_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPMonedaLayout.createSequentialGroup()
                                .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jT_050, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jT_025, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jT_010, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_005, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel23.setText("$");

        jLabel15.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel15.setText("Tarjetas de Crédito");

        jT_Debito.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Debito.setForeground(java.awt.Color.lightGray);
        jT_Debito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Debito.setText("0");
        jT_Debito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_DebitoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_DebitoFocusLost(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel25.setText("$");

        jLabel26.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel26.setText("$");

        jT_Credito.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Credito.setForeground(java.awt.Color.lightGray);
        jT_Credito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Credito.setText("0");
        jT_Credito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_CreditoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_CreditoFocusLost(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel22.setText("Tarjetas de Débito");

        jLabel27.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel27.setText("$");

        jT_Cheques.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Cheques.setForeground(java.awt.Color.lightGray);
        jT_Cheques.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Cheques.setText("0");
        jT_Cheques.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_ChequesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_ChequesFocusLost(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel28.setText("Cheques");

        jT_Arqueo.setEditable(false);
        jT_Arqueo.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Arqueo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Arqueo.setText("0");

        jLabel29.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14)); // NOI18N
        jLabel29.setText("Total del Arqueo");

        jLabel30.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel30.setText("$");

        jT_Egresos_Arqueo.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jT_Egresos_Arqueo.setForeground(java.awt.Color.lightGray);
        jT_Egresos_Arqueo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jT_Egresos_Arqueo.setText("0");
        jT_Egresos_Arqueo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_Egresos_ArqueoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_Egresos_ArqueoFocusLost(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel36.setText("Egresos");

        jLabel37.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel37.setText("$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jPMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jT_Resultado_Efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel36)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel37)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jT_Egresos_Arqueo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jT_Arqueo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jT_Credito, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jT_Debito))
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jT_Cheques)))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jT_Credito, jT_Debito});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Resultado_Efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jT_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jT_Debito, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jT_Cheques, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jT_Egresos_Arqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jT_Arqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FocoGanadoTextos(javax.swing.JTextField cajaTexto) {
        if (cajaTexto.getText().equals("0")) {
            cajaTexto.setText("");
            cajaTexto.setForeground(Color.black);
        }
    }

    private void FocoPerdidoTextos(javax.swing.JTextField cajaTexto) {
        if (cajaTexto.getText().isEmpty()) {
            cajaTexto.setText("0");
            cajaTexto.setForeground(Color.LIGHT_GRAY);
        }
        RecalcularMonto();
    }
    private void jT_100FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_100FocusLost
        FocoPerdidoTextos(jT_100);
    }//GEN-LAST:event_jT_100FocusLost

    private void jT_500FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_500FocusLost
        FocoPerdidoTextos(jT_500);


    }//GEN-LAST:event_jT_500FocusLost

    private void jT_50FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_50FocusLost
        FocoPerdidoTextos(jT_50);
    }//GEN-LAST:event_jT_50FocusLost

    private void jT_20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_20FocusLost
        FocoPerdidoTextos(jT_20);
    }//GEN-LAST:event_jT_20FocusLost

    private void jT_10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_10FocusLost
        FocoPerdidoTextos(jT_10);
    }//GEN-LAST:event_jT_10FocusLost

    private void jT_5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_5FocusLost
        FocoPerdidoTextos(jT_5);
    }//GEN-LAST:event_jT_5FocusLost

    private void jT_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_2FocusLost
        FocoPerdidoTextos(jT_2);
    }//GEN-LAST:event_jT_2FocusLost

    private void jT_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_1FocusLost
        FocoPerdidoTextos(jT_1);
    }//GEN-LAST:event_jT_1FocusLost

    private void jT_050FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_050FocusLost
        FocoPerdidoTextos(jT_050);
    }//GEN-LAST:event_jT_050FocusLost

    private void jT_025FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_025FocusLost
        FocoPerdidoTextos(jT_025);
    }//GEN-LAST:event_jT_025FocusLost

    private void jT_010FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_010FocusLost
        FocoPerdidoTextos(jT_010);
    }//GEN-LAST:event_jT_010FocusLost

    private void jT_005FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_005FocusLost
        FocoPerdidoTextos(jT_005);
    }//GEN-LAST:event_jT_005FocusLost

    private void jT_Sist_CajaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_Sist_CajaFocusGained

    }//GEN-LAST:event_jT_Sist_CajaFocusGained

    private void jT_Sist_EgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Sist_EgresosActionPerformed

    }//GEN-LAST:event_jT_Sist_EgresosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (JOptionPane.showConfirmDialog(this, "Finaliza el recuento de valores?", "Arqueo de Caja", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {

            for (int j = 0; j < jPMoneda.getComponentCount(); j++) {
                jPMoneda.getComponent(j).setEnabled(false);
            }
            for (int i = 0; i < jPanel3.getComponentCount(); i++) {
                jPanel3.getComponent(i).setEnabled(false);
            }

            HabilitarPanelArqueoSistema();
            Session sesion = HibernateUtil.getSessionFactory().openSession();

            Criteria query_caja = sesion.createCriteria(Caja_diaria.class);
            List<Caja_diaria> lista_caja = query_caja.list();

            int movimientosArqueo = ParametrosSistema.cantidadMovimientos + 1;
            query_caja.setFirstResult(lista_caja.size() - movimientosArqueo);
            query_caja.setMaxResults(movimientosArqueo);
            lista_caja = query_caja.list();

            Double efectivo = 0.00;
            Double creditos = 0.00;
            Double debitos = 0.00;
            Double cheques = 0.00;
            Double egresos = 0.00;
            Double Total = 0.00;
            Double caja = 0.00;

            for (int i = 0; i < lista_caja.size(); i++) {

                //TODO Revisar la forma en que se hacen los calculos de ingresos, egresos y demas
                Caja_diaria movimiento = lista_caja.get(i);
                jT_Sist_Total.setText(String.valueOf(movimiento.getSaldo()));
                if (movimiento.getConcepto().equals("Apertura de Caja")) {
                }
                switch (movimiento.getCategoria()) {
                    case 1:
                        //Aperturas
                        caja = Double.valueOf(movimiento.getSaldo());
                        break;
                    case 2:
                        //Ingresos manuales
                        efectivo = efectivo + movimiento.getHaber();
//                        egresos = egresos + movimiento.getDebe();
//                        egresos = egresos + movimiento.getDebe();
                        break;
                    case 3:
                        //Retiros
                        egresos = egresos + movimiento.getDebe();
                        break;
                    case 4:
                        //Gastos
                        egresos = egresos + movimiento.getDebe();
                        break;
                    case 5:
                        //Cuotas
                        switch (movimiento.getFormaPago().getIdFormaPago()) {
                            case 1:
                                //efectivo
                                efectivo = efectivo + movimiento.getHaber();
                                break;
                            case 2:
                                //Debito
                                debitos = debitos + movimiento.getHaber();
                                break;
                            case 3:
                                //Credito
                                creditos = creditos + movimiento.getHaber();
                                break;
                            case 4:
                                //Cheques
                                cheques = cheques + movimiento.getHaber();
                                break;
                            default:
                                break;
                        }
                        break;
                        case 6:
                        //Ventas
                        switch (movimiento.getFormaPago().getIdFormaPago()) {
                            case 1:
                                //efectivo
                                efectivo = efectivo + movimiento.getHaber();
                                break;
                            case 2:
                                //Debito
                                debitos = debitos + movimiento.getHaber();
                                break;
                            case 3:
                                //Credito
                                creditos = creditos + movimiento.getHaber();
                                break;
                            case 4:
                                //Cheques
                                cheques = cheques + movimiento.getHaber();
                                break;
                            default:
                                break;
                        }
                        break;
                    case 8:
                        break;
                    default:
                        break;
                }

            }
            jT_Sist_Caja.setText("");
            jT_Sist_Efectivo.setText(String.valueOf(efectivo));
            jT_Sist_Credito.setText(String.valueOf(creditos));
            jT_Sist_Debito.setText(String.valueOf(debitos));
            jT_Sist_Cheques.setText(String.valueOf(cheques));
            jT_Sist_Egresos.setText(String.valueOf(egresos));
            jT_Sist_Caja.setText(String.valueOf(caja));
            sesion.close();
            jB_CalcularDiferencias.setEnabled(rootPaneCheckingEnabled);
            jB_CalcularDiferencias.requestFocus();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void IngresosEfectivo() {

    }
    private void jT_CreditoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_CreditoFocusLost
        FocoPerdidoTextos(jT_Credito);
    }//GEN-LAST:event_jT_CreditoFocusLost

    private void jT_DebitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_DebitoFocusLost
        FocoPerdidoTextos(jT_Debito);
    }//GEN-LAST:event_jT_DebitoFocusLost

    private void jT_ChequesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_ChequesFocusLost
        FocoPerdidoTextos(jT_Cheques);
    }//GEN-LAST:event_jT_ChequesFocusLost

    private void jT_Egresos_ArqueoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_Egresos_ArqueoFocusLost
        FocoPerdidoTextos(jT_Egresos_Arqueo);
    }//GEN-LAST:event_jT_Egresos_ArqueoFocusLost

    private void jT_Dif_EgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Dif_EgresosActionPerformed

    }//GEN-LAST:event_jT_Dif_EgresosActionPerformed

    private void jT_500FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_500FocusGained
        FocoGanadoTextos(jT_500);
    }//GEN-LAST:event_jT_500FocusGained

    private void jT_100FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_100FocusGained
        FocoGanadoTextos(jT_100);
    }//GEN-LAST:event_jT_100FocusGained

    private void jT_50FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_50FocusGained
        FocoGanadoTextos(jT_50);
    }//GEN-LAST:event_jT_50FocusGained

    private void jT_20FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_20FocusGained
        FocoGanadoTextos(jT_20);
    }//GEN-LAST:event_jT_20FocusGained

    private void jT_10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_10FocusGained
        FocoGanadoTextos(jT_10);
    }//GEN-LAST:event_jT_10FocusGained

    private void jT_5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_5FocusGained
        FocoGanadoTextos(jT_5);
    }//GEN-LAST:event_jT_5FocusGained

    private void jT_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_2FocusGained
        FocoGanadoTextos(jT_2);
    }//GEN-LAST:event_jT_2FocusGained

    private void jT_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_1FocusGained
        FocoGanadoTextos(jT_1);
    }//GEN-LAST:event_jT_1FocusGained

    private void jT_050FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_050FocusGained
        FocoGanadoTextos(jT_050);
    }//GEN-LAST:event_jT_050FocusGained

    private void jT_025FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_025FocusGained
        FocoGanadoTextos(jT_025);
    }//GEN-LAST:event_jT_025FocusGained

    private void jT_010FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_010FocusGained
        FocoGanadoTextos(jT_010);
    }//GEN-LAST:event_jT_010FocusGained

    private void jT_005FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_005FocusGained
        FocoGanadoTextos(jT_005);
    }//GEN-LAST:event_jT_005FocusGained

    private void jT_CreditoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_CreditoFocusGained
        FocoGanadoTextos(jT_Credito);
    }//GEN-LAST:event_jT_CreditoFocusGained

    private void jT_DebitoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_DebitoFocusGained
        FocoGanadoTextos(jT_Debito);
    }//GEN-LAST:event_jT_DebitoFocusGained

    private void jT_ChequesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_ChequesFocusGained
        FocoGanadoTextos(jT_Cheques);
    }//GEN-LAST:event_jT_ChequesFocusGained

    private void jT_Egresos_ArqueoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_Egresos_ArqueoFocusGained
        FocoGanadoTextos(jT_Egresos_Arqueo);
    }//GEN-LAST:event_jT_Egresos_ArqueoFocusGained

    private void jB_CalcularDiferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CalcularDiferenciasActionPerformed
        HabilitarPanelDiferencia();
        CalcularDiferencias();
        jB_CerrarCaja.setEnabled(true);
    }//GEN-LAST:event_jB_CalcularDiferenciasActionPerformed

    private void jB_CerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CerrarCajaActionPerformed
        if (JOptionPane.showConfirmDialog(
                this, "Va a realizar el cierre de la caja. Esta acción no se puede deshacer.\n¿Desea continuar?", "Gestión de Caja",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.beginTransaction();

            if (!"".equals(jT_Dif_Total.getText())) {
                //Si hay diferencias en el arqueo del sistema y el fisico, guardar un registro de diferencia
                Caja_diaria diferencia = new Caja_diaria();

                FormasPago formaPago = new FormasPago();

                diferencia.setFecha(Date.from(Instant.now()));
                diferencia.setCategoria(8);
                diferencia.setConcepto("Diferencia de Arqueo");
                formaPago.setIdFormaPago(1);
                diferencia.setFormaPago(formaPago);
                if (Float.parseFloat(jT_Dif_Total.getText()) < 0) {
                    diferencia.setDebe(Float.parseFloat(jT_Dif_Total.getText()));
                } else {
                    diferencia.setHaber(Float.parseFloat(jT_Dif_Total.getText()));
                }
                diferencia.setSaldo(Float.parseFloat(jT_Arqueo.getText()));

                sesion.save(diferencia);
                ParametrosSistema.cantidadMovimientos++;

            }

            Caja_diaria cierre = new Caja_diaria();

            FormasPago formaPago = new FormasPago();

            cierre.setFecha(Date.from(Instant.now()));
            cierre.setCategoria(9);
            cierre.setConcepto("Cierre de Caja");
            formaPago.setIdFormaPago(1);
            cierre.setFormaPago(formaPago);
            cierre.setSaldo(Float.parseFloat(jT_Arqueo.getText()));

            sesion.save(cierre);
            ParametrosSistema.estadoCaja = 0;
            ParametrosSistema.cantidadMovimientos = 0;
            sesion.getTransaction().commit();
            sesion.close();
            ParametrosSistema.GuardaParametros();
            JOptionPane.showMessageDialog(this, "El cierre de caja se efectuó correctamente.", "Gestión de Caja", JOptionPane.INFORMATION_MESSAGE);
            this.getContentPane().removeAll();
            initComponents();
            jB_CerrarCaja.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Se canceló el cierre de caja. No se realizaron modificaciones", "Gestión de Caja", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jB_CerrarCajaActionPerformed

    private void CalcularDiferencias() {
        jT_Dif_Total.setText((String.valueOf(Double.parseDouble(jT_Arqueo.getText())
                - Double.parseDouble(jT_Sist_Total.getText()))));
        jT_Dif_Efectivo.setText((String.valueOf(Double.parseDouble(jT_Resultado_Efectivo.getText())
                - (Double.parseDouble(jT_Sist_Total.getText()) ))));
        jT_Dif_Debitos.setText((String.valueOf(Double.parseDouble(jT_Debito.getText())
                - Double.parseDouble(jT_Sist_Debito.getText()))));
        jT_Dif_Creditos.setText((String.valueOf(Double.parseDouble(jT_Credito.getText())
                - Double.parseDouble(jT_Sist_Credito.getText()))));
        jT_Dif_Cheques.setText((String.valueOf(Double.parseDouble(jT_Cheques.getText())
                - Double.parseDouble(jT_Sist_Cheques.getText()))));
        jT_Dif_Egresos.setText((String.valueOf(Double.parseDouble(jT_Egresos_Arqueo.getText())
                - Double.parseDouble(jT_Sist_Egresos.getText()))));

    }

    private void RecalcularMonto() {

        Double b500 = 500 * Double.parseDouble(jT_500.getText());
        Double b100 = 100 * Double.parseDouble(jT_100.getText());
        Double b50 = 50 * Double.parseDouble(jT_50.getText());
        Double b20 = 20 * Double.parseDouble(jT_20.getText());
        Double b10 = 10 * Double.parseDouble(jT_10.getText());
        Double b5 = 5 * Double.parseDouble(jT_5.getText());
        Double b2 = 2 * Double.parseDouble(jT_2.getText());
        Double m1 = Double.parseDouble(jT_1.getText());
        Double m50 = 0.50 * Double.parseDouble(jT_050.getText());
        Double m25 = 0.25 * Double.parseDouble(jT_025.getText());
        Double m10 = 0.10 * Double.parseDouble(jT_010.getText());
        Double m5 = 0.05 * Double.parseDouble(jT_005.getText());

        Double total = b500 + b100 + b50 + b20 + b10 + b5 + b2 + m1 + m50 + m25 + m10 + m5;

        jT_Resultado_Efectivo.setText(String.valueOf(total));

        Double arqueo = total + Double.parseDouble(jT_Credito.getText())
                + Double.parseDouble(jT_Debito.getText()) + Double.parseDouble(jT_Cheques.getText());
//                - Double.parseDouble(jT_Egresos_Arqueo.getText());
        jT_Arqueo.setText(arqueo.toString());
    }

    private void HabilitarPanelArqueoSistema() {
        for (int i = 0; i < jPMovimientosSistema.getComponentCount(); i++) {
            jPMovimientosSistema.getComponent(i).setEnabled(true);
        }
    }

    private void HabilitarPanelDiferencia() {
        for (int i = 0; i < jPResultado.getComponentCount(); i++) {
            jPResultado.getComponent(i).setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_CalcularDiferencias;
    private javax.swing.JButton jB_CerrarCaja;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPMoneda;
    private javax.swing.JPanel jPMovimientosSistema;
    private javax.swing.JPanel jPResultado;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jT_005;
    private javax.swing.JTextField jT_010;
    private javax.swing.JTextField jT_025;
    private javax.swing.JTextField jT_050;
    private javax.swing.JTextField jT_1;
    private javax.swing.JTextField jT_10;
    private javax.swing.JTextField jT_100;
    private javax.swing.JTextField jT_2;
    private javax.swing.JTextField jT_20;
    private javax.swing.JTextField jT_5;
    private javax.swing.JTextField jT_50;
    private javax.swing.JTextField jT_500;
    private javax.swing.JTextField jT_Arqueo;
    private javax.swing.JTextField jT_Cheques;
    private javax.swing.JTextField jT_Credito;
    private javax.swing.JTextField jT_Debito;
    private javax.swing.JTextField jT_Dif_Cheques;
    private javax.swing.JTextField jT_Dif_Creditos;
    private javax.swing.JTextField jT_Dif_Debitos;
    private javax.swing.JTextField jT_Dif_Efectivo;
    private javax.swing.JTextField jT_Dif_Egresos;
    private javax.swing.JTextField jT_Dif_Total;
    private javax.swing.JTextField jT_Egresos_Arqueo;
    private javax.swing.JTextField jT_Resultado_Efectivo;
    private javax.swing.JTextField jT_Sist_Caja;
    private javax.swing.JTextField jT_Sist_Cheques;
    private javax.swing.JTextField jT_Sist_Credito;
    private javax.swing.JTextField jT_Sist_Debito;
    private javax.swing.JTextField jT_Sist_Efectivo;
    private javax.swing.JTextField jT_Sist_Egresos;
    private javax.swing.JTextField jT_Sist_Total;
    // End of variables declaration//GEN-END:variables

}
