/*
 * Copyright 2016 Emiliano Policardo <www.facebook.com/policomputacion>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.lessence.gymmaven.GUI;

import com.lessence.gymmaven.clases.Caja_diaria;
import com.lessence.gymmaven.clases.HibernateUtil;
import com.lessence.gymmaven.clases.ParametrosSistema;
import com.lessence.gymmaven.clases.seteosGUI;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Emiliano Policardo <www.facebook.com/policomputacion>
 */
public class Form_Informes_Caja extends javax.swing.JFrame {

    /**
     * Creates new form Form_Informes_Caja
     */
    public Form_Informes_Caja() {
        initComponents();
        this.setLocationRelativeTo(null);
        ActualizarEstado();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMovimientos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlSaldo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlRetiros = new javax.swing.JLabel();
        jlGastos = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlEgresos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jlCuotas = new javax.swing.JLabel();
        jlVentas = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlIngresos = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jlIngresosManuales = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jlCajaInicial = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbMovimientos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jlCantidadMovimientos = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlRetiros1 = new javax.swing.JLabel();
        jlGastos1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jlEgresos1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jlCuotas1 = new javax.swing.JLabel();
        jlVentas1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jlIngresos1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jlIngresosManuales1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTMovimientosconFecha = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTMovimientos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jTMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Categoría", "Forma de Pago", "Debe", "Haber", "Saldo", "Concepto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTMovimientos.setColumnSelectionAllowed(true);
        jTMovimientos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTMovimientos);
        jTMovimientos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTMovimientos.getColumnModel().getColumnCount() > 0) {
            jTMovimientos.getColumnModel().getColumn(5).setHeaderValue("Saldo");
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel9.setText("Saldo Actual");

        jLabel14.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Situación actual de Movimientos");

        jlSaldo.setFont(new java.awt.Font("BankGothic Lt BT", 0, 48)); // NOI18N
        jlSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlSaldo.setText("0.00");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel19.setText("Retiros");

        jLabel10.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel10.setText("Gastos");

        jlRetiros.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlRetiros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlRetiros.setText("0.00");

        jlGastos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlGastos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlGastos.setText("0.00");

        jLabel16.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel16.setText("Total Egresos");

        jlEgresos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlEgresos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlEgresos.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel10))
                        .addGap(152, 152, 152))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlRetiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlEgresos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlRetiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlEgresos)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel17.setText("Total Ingresos");

        jLabel18.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel18.setText("Ventas");

        jlCuotas.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlCuotas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCuotas.setText("0.00");

        jlVentas.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlVentas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlVentas.setText("0.00");

        jLabel15.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel15.setText("Cuotas");

        jlIngresos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlIngresos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlIngresos.setText("0.00");

        jLabel20.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel20.setText("Ingresos Manuales");

        jlIngresosManuales.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlIngresosManuales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlIngresosManuales.setText("0.00");

        jLabel21.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel21.setText("Caja Inicial");

        jlCajaInicial.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlCajaInicial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCajaInicial.setText("0.00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(158, 158, 158))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(197, 197, 197))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlCuotas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlIngresosManuales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlCajaInicial, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jlIngresos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jlCajaInicial, jlCuotas, jlIngresos, jlIngresosManuales, jlVentas});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCuotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlIngresosManuales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jlCajaInicial))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jlIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSaldo)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Situación Actual", jPanel2);

        jDateChooser1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jDateChooser2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel1.setText("Desde");

        jLabel2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel2.setText("Hasta");

        jbMovimientos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jbMovimientos.setText("Mostrar Movimientos");
        jbMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMovimientosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad de movimientos registrados del periodo seleccionado");

        jlCantidadMovimientos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jlCantidadMovimientos.setText("999");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Resumen de movimientos segun fecha");

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel23.setText("Retiros");

        jLabel12.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel12.setText("Gastos");

        jlRetiros1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlRetiros1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlRetiros1.setText("0.00");

        jlGastos1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlGastos1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlGastos1.setText("0.00");

        jLabel24.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel24.setText("Total Egresos");

        jlEgresos1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlEgresos1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlEgresos1.setText("0.00");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel12))
                        .addGap(152, 152, 152))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlGastos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlRetiros1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlEgresos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlRetiros1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGastos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlEgresos1)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel25.setText("Total Ingresos");

        jLabel26.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel26.setText("Ventas");

        jlCuotas1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlCuotas1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCuotas1.setText("0.00");

        jlVentas1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlVentas1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlVentas1.setText("0.00");

        jLabel27.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel27.setText("Cuotas");

        jlIngresos1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlIngresos1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlIngresos1.setText("0.00");

        jLabel28.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel28.setText("Ingresos Manuales");

        jlIngresosManuales1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jlIngresosManuales1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlIngresosManuales1.setText("0.00");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(158, 158, 158))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(197, 197, 197))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCuotas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlIngresosManuales1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlIngresos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlVentas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCuotas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlIngresosManuales1))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jlIngresos1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTMovimientosconFecha.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jTMovimientosconFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Categoría", "Forma de Pago", "Debe", "Haber", "Concepto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTMovimientosconFecha.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTMovimientosconFecha);
        jTMovimientosconFecha.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlCantidadMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbMovimientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlCantidadMovimientos))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Movimientos entre Fechas", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarEstado() {
        float ventas = 0, cuotas = 0, ingresos = 0, apertura = 0,
                gastos = 0, retiros = 0, egresos = 0, ingresosManuales = 0;

        jlSaldo.setText(String.valueOf(Caja_diaria.saldoPrevio()));
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        DefaultTableModel modelo = (DefaultTableModel) jTMovimientos.getModel();
        modelo.setRowCount(0);
        Query query_caja = sesion.createQuery("From Caja_diaria");
        List<Caja_diaria> lista_caja = query_caja.list();

        query_caja.setFirstResult(lista_caja.size() - 1 - ParametrosSistema.cantidadMovimientos);
        query_caja.setMaxResults(ParametrosSistema.cantidadMovimientos + 1);
        lista_caja = query_caja.list();

        for (int i = 0; i < lista_caja.size(); i++) {

            Caja_diaria movimiento = lista_caja.get(i);
            int categorias = movimiento.getCategoria();
            String categoria = "";
            switch (categorias) {
                case 1:
                    categoria = "Apertura de Caja";
                    apertura = movimiento.getSaldo();
                    break;
                case 2:
                    categoria = "Ingreso manual";
                    ingresosManuales = ingresosManuales + movimiento.getHaber();
                    break;
                case 3:
                    categoria = "Retiro manual";
                    retiros = retiros + movimiento.getDebe();
                    break;
                case 4:
                    categoria = "Gastos";
                    gastos = gastos + movimiento.getDebe();
                    break;
                case 5:
                    categoria = "Cobro de Cuotas";
                    cuotas = cuotas + movimiento.getHaber();
                    break;
                case 6:
                    categoria = "Ventas";
                    ventas = ventas + movimiento.getHaber();
                    break;
                case 8:
                    categoria = "Diferencia de Arqueo";
                    break;
                case 9:
                    categoria = "Cierre de Caja";
                    break;
                default:
                    break;
            }
            Object[] fila = {seteosGUI.fechaCorta(movimiento.getFecha()), categoria,
                movimiento.getFormaPago().getFormaPago(), movimiento.getDebe(), movimiento.getHaber(),
                movimiento.getSaldo(), movimiento.getConcepto()};
            modelo.addRow(fila);
            ingresos = ingresos + movimiento.getHaber();
            egresos = egresos + movimiento.getDebe();

        }
        jlEgresos.setText(String.valueOf(egresos));
        jlIngresos.setText(String.valueOf(ingresos + apertura));
        jlVentas.setText(String.valueOf(ventas));
        jlGastos.setText(String.valueOf(gastos));
        jlIngresosManuales.setText(String.valueOf(ingresosManuales));
        jlCuotas.setText(String.valueOf(cuotas));
        jlRetiros.setText(String.valueOf(retiros));
        jlCajaInicial.setText(String.valueOf(apertura));

        sesion.close();

    }

    private void jbMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMovimientosActionPerformed

        float ventas = 0, cuotas = 0, ingresos = 0, apertura = 0,
                gastos = 0, retiros = 0, egresos = 0, ingresosManuales = 0;
        String categoria = "";
        DefaultTableModel modelo = (DefaultTableModel) jTMovimientosconFecha.getModel();
        modelo.setRowCount(0);

        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();
        String HQL_QUERY = "select c from Caja_diaria c where c.fecha between :start and :end ";
        String HQL_Query_Sumatoria = "select sum(debe) from Caja_diaria s where s.fecha between :start and :end ";
        Query query = sesion.createQuery(HQL_QUERY);
        Query queryConsulta = sesion.createQuery(HQL_Query_Sumatoria);
        Date dateFrom = jDateChooser1.getDate();
        Date dateTo = jDateChooser2.getDate();
        query.setParameter("start", dateFrom);
        queryConsulta.setParameter("start", dateFrom);
        query.setParameter("end", dateTo);
        queryConsulta.setParameter("end", dateTo);
        List list = queryConsulta.list();

        List<Caja_diaria> result = query.list();
        for (int i = 0; i < result.size(); i++) {
            Caja_diaria registro = (Caja_diaria) result.get(i);
            int categorias = registro.getCategoria();


            switch (categorias) {
                case 2:
                    categoria = "Ingreso manual";
                    ingresosManuales = ingresosManuales + registro.getHaber();
                    break;
                case 3:
                    categoria = "Retiro manual";
                    retiros = retiros + registro.getDebe();
                    break;
                case 4:
                    categoria = "Gastos";
                    gastos = gastos + registro.getDebe();
                    break;
                case 5:
                    categoria = "Cobro de Cuotas";
                    cuotas = cuotas + registro.getHaber();
                    break;
                case 6:
                    categoria = "Ventas";
                    ventas = ventas + registro.getHaber();
                    break;
                case 8:
                    categoria = "Diferencia de Arqueo";
                    break;
                case 9:
                    categoria = "Cierre de Caja";
                    break;
                default:
                    break;
            }
            Object[] fila = {seteosGUI.fechaCorta(registro.getFecha()), categoria, registro.getFormaPago().getFormaPago(), registro.getDebe(), registro.getHaber(), registro.getConcepto()};
            modelo.addRow(fila);

            ingresos = ingresos + registro.getHaber();
            egresos = egresos + registro.getDebe();

        }
        jlEgresos1.setText(String.valueOf(egresos));
        jlIngresos1.setText(String.valueOf(ingresos));
        jlVentas1.setText(String.valueOf(ventas));
        jlGastos1.setText(String.valueOf(gastos));
        jlIngresosManuales1.setText(String.valueOf(ingresosManuales));
        jlCuotas1.setText(String.valueOf(cuotas));
        jlRetiros1.setText(String.valueOf(retiros));
//        jlSaldo1.setText(String.valueOf(ingresos - egresos));
        jlCantidadMovimientos.setText(String.valueOf(result.size()));

        sesion.close();
    }//GEN-LAST:event_jbMovimientosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTMovimientos;
    private javax.swing.JTable jTMovimientosconFecha;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbMovimientos;
    private javax.swing.JLabel jlCajaInicial;
    private javax.swing.JLabel jlCantidadMovimientos;
    private javax.swing.JLabel jlCuotas;
    private javax.swing.JLabel jlCuotas1;
    private javax.swing.JLabel jlEgresos;
    private javax.swing.JLabel jlEgresos1;
    private javax.swing.JLabel jlGastos;
    private javax.swing.JLabel jlGastos1;
    private javax.swing.JLabel jlIngresos;
    private javax.swing.JLabel jlIngresos1;
    private javax.swing.JLabel jlIngresosManuales;
    private javax.swing.JLabel jlIngresosManuales1;
    private javax.swing.JLabel jlRetiros;
    private javax.swing.JLabel jlRetiros1;
    private javax.swing.JLabel jlSaldo;
    private javax.swing.JLabel jlVentas;
    private javax.swing.JLabel jlVentas1;
    // End of variables declaration//GEN-END:variables
}
