/*
 * Form_Consulta_Profesores.java
 *
 * Created on 10 de junio de 2015, 15:57
 */
package com.lessence.gymmaven.GUI;

import com.lessence.gymmaven.clases.HibernateUtil;
import com.lessence.gymmaven.clases.Profesores;
import com.lessence.gymmaven.clases.RegistroAsistenciasProfesores;
import com.lessence.gymmaven.clases.Relaciones;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Session;

/**
 *
 * @author Emiliano
 */
public class Form_Consulta_Profesores extends javax.swing.JDialog {

    /**
     * Creates new form ConsultaProfesores
     */
    public Form_Consulta_Profesores() {
        initComponents();
        ActualizarGrillaProfesores();
        this.setLocationRelativeTo(null);
        jbConsultaAlumnos.setEnabled(false);
        jBActividades.setEnabled(false);
        //ProfeSeleccionado(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jBNuevoProfesor = new javax.swing.JButton();
        jBModificarProfesores = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFiltraProfesores = new javax.swing.JTextField();
        jTFiltraApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCEstados = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTFiltraNombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTActividades = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTablaProfesores = new javax.swing.JTable();
        jBActividades = new javax.swing.JButton();
        jbConsultaAlumnos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBNuevoProfesor.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jBNuevoProfesor.setText("Agregar Nuevo Profesor");
        jBNuevoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoProfesorActionPerformed(evt);
            }
        });

        jBModificarProfesores.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jBModificarProfesores.setText("Modificar Datos");
        jBModificarProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarProfesoresActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));

        jLabel3.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel3.setText("Documento");

        jTFiltraProfesores.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jTFiltraProfesores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFiltraProfesoresKeyReleased(evt);
            }
        });

        jTFiltraApellido.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jTFiltraApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFiltraApellidoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel4.setText("Apellido");

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel1.setText("Estado");

        jCEstados.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jCEstados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Activos", "Inactivos" }));

        jLabel2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jTFiltraNombre.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jTFiltraNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFiltraNombreKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTFiltraProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFiltraApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFiltraNombre)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFiltraProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFiltraApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFiltraNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Acceso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Actividades", "Horarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTActividadesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTActividades);

        jScrollPane8.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jScrollPane8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane8MouseClicked(evt);
            }
        });

        jTablaProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Apellido y Nombre", "Celular", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaProfesoresMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTablaProfesores);

        jBActividades.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jBActividades.setText("Gestión de Actividades del Profesor");
        jBActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActividadesActionPerformed(evt);
            }
        });

        jbConsultaAlumnos.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jbConsultaAlumnos.setText("Consultar Alumnos del Profesor");
        jbConsultaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jBActividades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbConsultaAlumnos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBActividades)
                    .addComponent(jbConsultaAlumnos))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBModificarProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBNuevoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBModificarProfesores, jBNuevoProfesor});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBNuevoProfesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBModificarProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBModificarProfesores, jBNuevoProfesor});

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoProfesorActionPerformed
        new Form_ABMProfesores().setVisible(true);
    }//GEN-LAST:event_jBNuevoProfesorActionPerformed

    private void jBModificarProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarProfesoresActionPerformed
        if (jTablaProfesores.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero el profesor a modificar");
        } else {
//            String Socio = ;
            new Form_ABMProfesores(jTablaProfesores.getValueAt(jTablaProfesores.getSelectedRow(), 0).toString()).setVisible(true);
        }
    }//GEN-LAST:event_jBModificarProfesoresActionPerformed

    private void ProfeSeleccionado(String DNI) {

        int i = 0;
        int j = 0;
        int k = 0;
        int l = 0;
        DefaultTableModel TablaActividades = (DefaultTableModel) jTActividades.getModel();
        TablaActividades.setRowCount(i);
        DefaultTableModel TablaCuenta = (DefaultTableModel) jTable1.getModel();
        TablaCuenta.setRowCount(k);

        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Criteria consulta = sesion.createCriteria(RegistroAsistenciasProfesores.class);
        List<RegistroAsistenciasProfesores> asistencias = consulta.list();
        for (int m = 0; m < asistencias.size(); m++) {
            RegistroAsistenciasProfesores registro = asistencias.get(m);
            String DNI_Obtenido = registro.getProfesor().getPersona().getDNI();
            if (DNI_Obtenido.equals(DNI)) {
                String tiempoRegistro = new SimpleDateFormat("dd-MM-yyyy - HH:mm:ss").format(registro.getFecha());

                Object[] fila = {tiempoRegistro};
                TablaCuenta.addRow(fila);
            }
        }
        Criteria consultaRelacion = sesion.createCriteria(Relaciones.class);
        List<Relaciones> listaRelaciones = consultaRelacion.list();
        for (int h = 0; h < listaRelaciones.size(); h++) {
            Relaciones relacion = listaRelaciones.get(h);
            if (relacion.getProfesor().getPersona().getDNI().equals(DNI)) {
                Object[] fila = {relacion.getActividad().getActividad(),
                    relacion.getHorario().getHorario()};
                TablaActividades.addRow(fila);
            }
        }
        jBActividades.setEnabled(true);
        jbConsultaAlumnos.setEnabled(true);

    }


    private void jTFiltraProfesoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFiltraProfesoresKeyReleased
        ActualizarGrillaProfesores();
    }//GEN-LAST:event_jTFiltraProfesoresKeyReleased

    private void jTFiltraApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFiltraApellidoKeyReleased
        ActualizarGrillaProfesores();
    }//GEN-LAST:event_jTFiltraApellidoKeyReleased

    private void jTFiltraNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFiltraNombreKeyReleased
        ActualizarGrillaProfesores();
    }//GEN-LAST:event_jTFiltraNombreKeyReleased

    private void jTActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTActividadesMouseClicked

    }//GEN-LAST:event_jTActividadesMouseClicked

    private void jScrollPane8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane8MouseClicked

    }//GEN-LAST:event_jScrollPane8MouseClicked

    private void jTablaProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaProfesoresMouseClicked
        String Socio = jTablaProfesores.getValueAt(jTablaProfesores.getSelectedRow(), 0).toString();
        ProfeSeleccionado(Socio);

    }//GEN-LAST:event_jTablaProfesoresMouseClicked

    private void jBActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActividadesActionPerformed
        Form_Relaciona_Actividades_Turnos_Profesores act = new Form_Relaciona_Actividades_Turnos_Profesores(null, rootPaneCheckingEnabled);
        act.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBActividadesActionPerformed

    private void jbConsultaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaAlumnosActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTablaProfesores.getModel();
        String dni = modelo.getValueAt(jTablaProfesores.getSelectedRow(), 0).toString();
        Form_ConsultaAlumnosProfe consulta = new Form_ConsultaAlumnosProfe(dni);
        consulta.setVisible(true);

    }//GEN-LAST:event_jbConsultaAlumnosActionPerformed

    private void ActualizarGrillaProfesores() {

        Session sesion = HibernateUtil.getSessionFactory().openSession();
        DefaultTableModel modelo = (DefaultTableModel) jTablaProfesores.getModel();
        modelo.setRowCount(0);

        Criteria query_profesores = sesion.createCriteria(Profesores.class);
        List<Profesores> lista_profesores = query_profesores.list();
        for (int i = 0; i < lista_profesores.size(); i++) {
            if (lista_profesores.isEmpty()) {

            } else {
                Profesores profesor = lista_profesores.get(i);
                String DNI = profesor.getPersona().getDNI();
                String Profesor = profesor.getPersona().getApellido() + " "
                        + profesor.getPersona().getNombre();
                String Celular = profesor.getPersona().getCelular();
                String Correo = profesor.getPersona().getCorreo();
                Object[] fila = {DNI, Profesor, Celular, Correo};
                modelo.addRow(fila);
            }

        }
        sesion.close();
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActividades;
    private javax.swing.JButton jBModificarProfesores;
    private javax.swing.JButton jBNuevoProfesor;
    private javax.swing.JComboBox jCEstados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTActividades;
    private javax.swing.JTextField jTFiltraApellido;
    private javax.swing.JTextField jTFiltraNombre;
    private javax.swing.JTextField jTFiltraProfesores;
    private javax.swing.JTable jTablaProfesores;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbConsultaAlumnos;
    // End of variables declaration//GEN-END:variables

}
