/*
 * Copyright 2016 Emiliano Policardo http://www.facebook.com/policomputacion.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.lessence.gymmaven.GUI;

import com.lessence.gymmaven.clases.Caja_diaria;
import com.lessence.gymmaven.clases.FormasPago;
import com.lessence.gymmaven.clases.Gastos;
import com.lessence.gymmaven.clases.HibernateUtil;
import com.lessence.gymmaven.clases.ParametrosSistema;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Emiliano Policardo http://www.facebook.com/policomputacion
 */
public class Form_Gastos_Visual extends javax.swing.JFrame {

    /**
     * Creates new form Form_Gastos_Visual
     */
    public Form_Gastos_Visual() {
        initComponents();
        ActualizarGrilla();
        jDCFecha.setDate(Date.from(Instant.now()));
        jDCFecha1.setDate(Date.from(Instant.now()));
        jDCFecha_IngresoManual.setDate(Date.from(Instant.now()));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTConcepto = new javax.swing.JTextField();
        jBGrabar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jCCategorias = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtImporte = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTConcepto1 = new javax.swing.JTextField();
        jBGrabar_Retiros = new javax.swing.JButton();
        jBModificar1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDCFecha1 = new com.toedter.calendar.JDateChooser();
        jtImporte1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTConcepto_IngresoManual = new javax.swing.JTextField();
        jBGrabar_IngresoManual = new javax.swing.JButton();
        jBModificar2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDCFecha_IngresoManual = new com.toedter.calendar.JDateChooser();
        jt_Ingresos_Importe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTgastos = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel1.setText("Fecha");

        jLabel2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel2.setText("Concepto");

        jLabel4.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel4.setText("Importe");

        jTConcepto.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jBGrabar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14)); // NOI18N
        jBGrabar.setText("Grabar");
        jBGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGrabarActionPerformed(evt);
            }
        });

        jBModificar.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jBModificar.setText("Modificar");

        jButton3.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jButton3.setText("Cancelar");

        jDCFecha.setDateFormatString("dd-MM-yyyy");
        jDCFecha.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jCCategorias.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jCCategorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Generales", "Alquiler", "Sueldos", "Mejoras" }));

        jLabel3.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel3.setText("Categoria");

        jtImporte.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTConcepto))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                        .addComponent(jBGrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBGrabar)
                            .addComponent(jBModificar)
                            .addComponent(jButton3)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Gastos", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel5.setText("Fecha");

        jLabel6.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel6.setText("Concepto");

        jLabel7.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel7.setText("Importe");

        jTConcepto1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jBGrabar_Retiros.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14)); // NOI18N
        jBGrabar_Retiros.setText("Grabar");
        jBGrabar_Retiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGrabar_RetirosActionPerformed(evt);
            }
        });

        jBModificar1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jBModificar1.setText("Modificar");

        jButton4.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jButton4.setText("Cancelar");

        jDCFecha1.setDateFormatString("dd-MM-yyyy");
        jDCFecha1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 595, Short.MAX_VALUE)
                        .addComponent(jBGrabar_Retiros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBModificar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jDCFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jtImporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTConcepto1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTConcepto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtImporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGrabar_Retiros)
                    .addComponent(jBModificar1)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Retiros Manuales", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel8.setText("Fecha");

        jLabel9.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel9.setText("Concepto");

        jLabel10.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jLabel10.setText("Importe");

        jTConcepto_IngresoManual.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jBGrabar_IngresoManual.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14)); // NOI18N
        jBGrabar_IngresoManual.setText("Grabar");
        jBGrabar_IngresoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGrabar_IngresoManualActionPerformed(evt);
            }
        });

        jBModificar2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jBModificar2.setText("Modificar");

        jButton5.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jButton5.setText("Cancelar");

        jDCFecha_IngresoManual.setDateFormatString("dd-MM-yyyy");
        jDCFecha_IngresoManual.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jDCFecha_IngresoManual, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jt_Ingresos_Importe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jBGrabar_IngresoManual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBModificar2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5))
                                    .addComponent(jTConcepto_IngresoManual, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE))
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(873, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTConcepto_IngresoManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCFecha_IngresoManual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGrabar_IngresoManual)
                    .addComponent(jBModificar2)
                    .addComponent(jButton5)
                    .addComponent(jt_Ingresos_Importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ingresos Manuales", jPanel3);

        jScrollPane1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N

        jTgastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Tipo", "Concepto", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTgastos);
        if (jTgastos.getColumnModel().getColumnCount() > 0) {
            jTgastos.getColumnModel().getColumn(2).setPreferredWidth(400);
        }

        jLabel11.setText("Balance de caja, mostrando importes de gastos, ingresos, ventas descuentos y demas");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ActualizarGrilla() {

        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Query consulta = sesion.createQuery("FROM Gastos");
        List<Gastos> listaGastos = consulta.list();
        DefaultTableModel tabla = (DefaultTableModel) jTgastos.getModel();
        tabla.setRowCount(0);
        for (int i = 0; i < listaGastos.size(); i++) {
            Gastos gasto = listaGastos.get(i);
            String tipo = "";
            switch (gasto.getTipo()) {
                case 0:
                    tipo = "Generales";
                    break;
                case 1:
                    tipo = "Alquiler";
                    break;
                case 2:
                    tipo = "Sueldos";
                    break;
                case 3:
                    tipo = "Mejoras";
                    break;

            }
            Object[] fila = {gasto.getFecha(), tipo, gasto.getConcepto(), gasto.getImporte()};
            tabla.addRow(fila);
        }

    }

    public void GrabarIngresoManual(int categoria, float Importe, String Concepto, Date fecha) {

        int idCategoria = jCCategorias.getSelectedIndex();

        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Query consulta = sesion.createQuery("FROM Caja_diaria");
        List<Caja_diaria> caja = consulta.list();
        int ultimo_registro = caja.size();
        float saldo;
        if (caja.size() == 0) {
            saldo = 0;
        } else {
            saldo = caja.get(ultimo_registro - 1).getSaldo();
        }
        sesion.beginTransaction();
        Caja_diaria registro = new Caja_diaria();
        FormasPago formaPago = new FormasPago();
        formaPago.setIdFormaPago(1); //Gastos se realizan desde el efectivo
        registro.setFecha(fecha);
        registro.setFormaPago(formaPago);
        registro.setCategoria(categoria); // 2 - Ingresos Manuales / 3 - Retiro Manual  // 4 - Gastos
        registro.setConcepto(Concepto);
        registro.setHaber(Importe);
        registro.setSaldo(saldo + Importe);
        sesion.save(registro);
        sesion.getTransaction().commit();
        sesion.close();

        ActualizarGrilla();
        ParametrosSistema.cantidadMovimientos = ParametrosSistema.cantidadMovimientos + 1;
        ParametrosSistema.GuardaParametros();
    }

    public void GrabarGastos(int categoria, float Importe, String Concepto, Date fecha) {

        int idCategoria = jCCategorias.getSelectedIndex();

        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Query consulta = sesion.createQuery("FROM Caja_diaria");
        List<Caja_diaria> caja = consulta.list();
        int ultimo_registro = caja.size();
        float saldo;
        if (caja.size() == 0) {
            saldo = 0;
        } else {
            saldo = caja.get(ultimo_registro - 1).getSaldo();
        }
        sesion.beginTransaction();
        Gastos gastonuevo = new Gastos();
        gastonuevo.setFecha(fecha);
        gastonuevo.setConcepto(Concepto);
        gastonuevo.setImporte(Importe);
        gastonuevo.setTipo(idCategoria);
        sesion.save(gastonuevo);
        Caja_diaria registro = new Caja_diaria();
        FormasPago formaPago = new FormasPago();
        formaPago.setIdFormaPago(1); //Gastos se realizan desde el efectivo
        registro.setFecha(fecha);
        registro.setFormaPago(formaPago);
        registro.setCategoria(categoria); // Retiro Manual 3 // Gastos 4
        registro.setConcepto(Concepto);

        registro.setDebe(Importe);
        registro.setSaldo(saldo - Importe);
        sesion.save(registro);
        sesion.getTransaction().commit();
        sesion.close();

        ActualizarGrilla();
        ParametrosSistema.cantidadMovimientos = ParametrosSistema.cantidadMovimientos + 1;
        ParametrosSistema.GuardaParametros();
    }


    private void jBGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGrabarActionPerformed

        float Importe = Float.valueOf(jtImporte.getText());
        String Concepto = jTConcepto.getText();
        Date fecha = jDCFecha.getDate();
        if (ParametrosSistema.estadoCaja == 0) {
            if (JOptionPane.showConfirmDialog(this, "La caja diaria no fue abierta.\nNo puede realizar movimientos financieros hasta tanto haga la apertura. \nDesea"
                    + " efectuar la apertura de caja?", "Carga de pagos", JOptionPane.YES_NO_OPTION) == 0) {
                ParametrosSistema.estadoCaja = 1;
                ParametrosSistema.GuardaParametros();
                Caja_diaria.AbrirCaja();
                JOptionPane.showMessageDialog(this, "La apertura de caja se realizó correctamente", "Gestión de Caja Diaria", JOptionPane.INFORMATION_MESSAGE);

                if (JOptionPane.showConfirmDialog(this, "Desea continuar con el asiento del movimiento?", "Carga de pagos", JOptionPane.YES_NO_OPTION) == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Canceló la operacion");
                } else {
                    GrabarGastos(4, Importe, Concepto, fecha);
                    JOptionPane.showMessageDialog(this, "El gasto fue cargado");
                    initComponents();
                    jDCFecha.setDate(Date.from(Instant.now()));
                    jDCFecha1.setDate(Date.from(Instant.now()));
                    jDCFecha_IngresoManual.setDate(Date.from(Instant.now()));
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Canceló la apertura de caja");
            }

        } else {
            GrabarGastos(4, Importe, Concepto, fecha);
            JOptionPane.showMessageDialog(this, "El gasto fue cargado");
            initComponents();
            jDCFecha.setDate(Date.from(Instant.now()));
            jDCFecha1.setDate(Date.from(Instant.now()));
            jDCFecha_IngresoManual.setDate(Date.from(Instant.now()));
        }
    }//GEN-LAST:event_jBGrabarActionPerformed

    private void jBGrabar_RetirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGrabar_RetirosActionPerformed
        float Importe = Float.valueOf(jtImporte1.getText());
        String Concepto = jTConcepto1.getText();
        Date fecha = jDCFecha1.getDate();
        if (ParametrosSistema.estadoCaja == 0) {
            if (JOptionPane.showConfirmDialog(this, "La caja diaria no fue abierta.\nNo puede realizar movimientos financieros hasta tanto haga la apertura. \nDesea"
                    + " efectuar la apertura de caja?", "Carga de pagos", JOptionPane.YES_NO_OPTION) == 0) {
                ParametrosSistema.estadoCaja = 1;
                ParametrosSistema.GuardaParametros();
                Caja_diaria.AbrirCaja();
                JOptionPane.showMessageDialog(this, "La apertura de caja se realizó correctamente", "Gestión de Caja Diaria", JOptionPane.INFORMATION_MESSAGE);

                if (JOptionPane.showConfirmDialog(this, "Desea continuar con el asiento del movimiento?", "Carga de pagos", JOptionPane.YES_NO_OPTION) == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Canceló la operacion");
                } else {
                    GrabarGastos(3, Importe, Concepto, fecha);
                    JOptionPane.showMessageDialog(this, "El retiro fue grabado con éxito");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Canceló la apertura de caja");
            }

        } else {
            GrabarGastos(3, Importe, Concepto, fecha);
            JOptionPane.showMessageDialog(this, "El retiro fue grabado con éxito");
        }
    }//GEN-LAST:event_jBGrabar_RetirosActionPerformed

    private void jBGrabar_IngresoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGrabar_IngresoManualActionPerformed
        float Importe = Float.valueOf(jt_Ingresos_Importe.getText());
        String Concepto = jTConcepto_IngresoManual.getText();
        Date fecha = jDCFecha_IngresoManual.getDate();
        GrabarIngresoManual(2, Importe, Concepto, fecha);
        JOptionPane.showMessageDialog(this, "El ingreso manual fue grabado con éxito");

    }//GEN-LAST:event_jBGrabar_IngresoManualActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGrabar;
    private javax.swing.JButton jBGrabar_IngresoManual;
    private javax.swing.JButton jBGrabar_Retiros;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBModificar1;
    private javax.swing.JButton jBModificar2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jCCategorias;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private com.toedter.calendar.JDateChooser jDCFecha1;
    private com.toedter.calendar.JDateChooser jDCFecha_IngresoManual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTConcepto;
    private javax.swing.JTextField jTConcepto1;
    private javax.swing.JTextField jTConcepto_IngresoManual;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTgastos;
    private javax.swing.JTextField jtImporte;
    private javax.swing.JTextField jtImporte1;
    private javax.swing.JTextField jt_Ingresos_Importe;
    // End of variables declaration//GEN-END:variables
}
